/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    articles: Article;
    members: Member;
    events: Event;
    partners: Partner;
    contact_requests: ContactRequest;
    membership_requests: MembershipRequest;
    newsletter_subscriptions: NewsletterSubscription;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    contact_requests: ContactRequestsSelect<false> | ContactRequestsSelect<true>;
    membership_requests: MembershipRequestsSelect<false> | MembershipRequestsSelect<true>;
    newsletter_subscriptions: NewsletterSubscriptionsSelect<false> | NewsletterSubscriptionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'annual-statistics': AnnualStatistic;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'annual-statistics': AnnualStatisticsSelect<false> | AnnualStatisticsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  status: 'draft' | 'published' | 'archived';
  sort?: number | null;
  title_en: string;
  title_fr: string;
  excerpt_en: string;
  excerpt_fr: string;
  content_en: string;
  content_fr: string;
  category: 'Innovation' | 'Climate & Tech' | 'Inclusion' | 'Tech & Society';
  author: string;
  published_at: string;
  image?: (number | null) | Media;
  /**
   * Utilisée uniquement tant qu'aucun média n'est téléversé.
   */
  local_image?: string | null;
  source_url: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  status: 'draft' | 'published' | 'archived';
  sort?: number | null;
  slug: string;
  code: string;
  name_en: string;
  name_fr: string;
  member_status: 'verified' | 'onboarding';
  focus_en: string;
  focus_fr: string;
  description_en?: string | null;
  description_fr?: string | null;
  about_en?: string | null;
  about_fr?: string | null;
  association_name_en?: string | null;
  association_name_fr?: string | null;
  website_url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  status: 'draft' | 'published' | 'archived';
  sort?: number | null;
  key: string;
  title_en: string;
  title_fr: string;
  starts_at: string;
  ends_at: string;
  location_en: string;
  location_fr: string;
  description_en: string;
  description_fr: string;
  link: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  status: 'draft' | 'published' | 'archived';
  sort?: number | null;
  name: string;
  website_url?: string | null;
  logo?: (number | null) | Media;
  /**
   * Utilisé uniquement tant qu'aucun logo n'est téléversé.
   */
  local_image?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_requests".
 */
export interface ContactRequest {
  id: number;
  request_status: 'new' | 'processed' | 'spam';
  full_name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership_requests".
 */
export interface MembershipRequest {
  id: number;
  request_status: 'new' | 'processed' | 'rejected' | 'spam';
  membership_type: 'National ecosystem' | 'Partner organization' | 'Individual supporter';
  full_name: string;
  email: string;
  phone?: string | null;
  applicant_role?: string | null;
  country: string;
  organization: string;
  organization_type?: string | null;
  org_website?: string | null;
  community_size?: string | null;
  focus_area?: string | null;
  contributions?: string | null;
  interest: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_subscriptions".
 */
export interface NewsletterSubscription {
  id: number;
  request_status: 'new' | 'subscribed' | 'unsubscribed';
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'contact_requests';
        value: number | ContactRequest;
      } | null)
    | ({
        relationTo: 'membership_requests';
        value: number | MembershipRequest;
      } | null)
    | ({
        relationTo: 'newsletter_subscriptions';
        value: number | NewsletterSubscription;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  status?: T;
  sort?: T;
  title_en?: T;
  title_fr?: T;
  excerpt_en?: T;
  excerpt_fr?: T;
  content_en?: T;
  content_fr?: T;
  category?: T;
  author?: T;
  published_at?: T;
  image?: T;
  local_image?: T;
  source_url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  status?: T;
  sort?: T;
  slug?: T;
  code?: T;
  name_en?: T;
  name_fr?: T;
  member_status?: T;
  focus_en?: T;
  focus_fr?: T;
  description_en?: T;
  description_fr?: T;
  about_en?: T;
  about_fr?: T;
  association_name_en?: T;
  association_name_fr?: T;
  website_url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  status?: T;
  sort?: T;
  key?: T;
  title_en?: T;
  title_fr?: T;
  starts_at?: T;
  ends_at?: T;
  location_en?: T;
  location_fr?: T;
  description_en?: T;
  description_fr?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  status?: T;
  sort?: T;
  name?: T;
  website_url?: T;
  logo?: T;
  local_image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_requests_select".
 */
export interface ContactRequestsSelect<T extends boolean = true> {
  request_status?: T;
  full_name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership_requests_select".
 */
export interface MembershipRequestsSelect<T extends boolean = true> {
  request_status?: T;
  membership_type?: T;
  full_name?: T;
  email?: T;
  phone?: T;
  applicant_role?: T;
  country?: T;
  organization?: T;
  organization_type?: T;
  org_website?: T;
  community_size?: T;
  focus_area?: T;
  contributions?: T;
  interest?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_subscriptions_select".
 */
export interface NewsletterSubscriptionsSelect<T extends boolean = true> {
  request_status?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  hero_eyebrow_en: string;
  hero_eyebrow_fr: string;
  hero_title_en: string;
  hero_title_fr: string;
  hero_description_en: string;
  hero_description_fr: string;
  contact_email: string;
  secretariat_email: string;
  phone: string;
  address: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Synthèse annuelle de l'avancement de la robotique en Afrique. Le site public l'affiche sur /statistics et propose le PDF au téléchargement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-statistics".
 */
export interface AnnualStatistic {
  id: number;
  year: number;
  updated_at?: string | null;
  summary_en: string;
  summary_fr: string;
  methodology_en: string;
  methodology_fr: string;
  /**
   * Téléverser le PDF du rapport annuel (facultatif tant qu'il n'est pas prêt).
   */
  report?: (number | null) | Media;
  /**
   * Un indicateur par ligne (associations, éducation, recherche, entreprises, événements, industrie, financement, politiques…).
   */
  categories?:
    | {
        key: string;
        label_en: string;
        label_fr: string;
        /**
         * Ex. « 20 », « 140+ », « US$18M ».
         */
        value: string;
        delta_en?: string | null;
        delta_fr?: string | null;
        description_en: string;
        description_fr: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  hero_eyebrow_en?: T;
  hero_eyebrow_fr?: T;
  hero_title_en?: T;
  hero_title_fr?: T;
  hero_description_en?: T;
  hero_description_fr?: T;
  contact_email?: T;
  secretariat_email?: T;
  phone?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-statistics_select".
 */
export interface AnnualStatisticsSelect<T extends boolean = true> {
  year?: T;
  updated_at?: T;
  summary_en?: T;
  summary_fr?: T;
  methodology_en?: T;
  methodology_fr?: T;
  report?: T;
  categories?:
    | T
    | {
        key?: T;
        label_en?: T;
        label_fr?: T;
        value?: T;
        delta_en?: T;
        delta_fr?: T;
        description_en?: T;
        description_fr?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}